spring.application.name=EVCar

spring.datasource.url=jdbc:mysql://evcar-db.c3uqycec095l.ap-northeast-2.rds.amazonaws.com:3306/evcar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=eunha
spring.datasource.password=15712468qwe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=never

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

fastapi.base-url=http://127.0.0.1:8000

ev.map.kakao.javascript-key=cf48cee8b8504512773dad65b451632a
ev.public-api.evcharger.base-url=http://apis.data.go.kr/B552584/EvCharger
ev.public-api.evcharger.service-key=8ee9755d5fedd3227facadb4400a90b17d51a67c0f325639a560e309b2f648fb
ev.public-api.evcharger.zcodes=11,26,27,28,29,30,31,36,41,43,44,46,47,48,50,51,52

