spring.application.name=EVCar

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=never

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

fastapi.base-url=${FASTAPI_BASE_URL}

ev.map.kakao.javascript-key=${KAKAO_JS_KEY}
ev.public-api.evcharger.base-url=${EV_API_BASE_URL}
ev.public-api.evcharger.service-key=${EV_API_SERVICE_KEY}
ev.public-api.evcharger.zcodes=${EV_API_ZCODES}